.DELETE_ON_ERROR:

all: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R5.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK: 
	rm -f -r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT
	mkdir -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT
	cp -f /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/InitValues6.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current
	> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt
	> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.0.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFH_REGION_1KG.vcf.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFH_REGION_1KG.gz -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFH_REGION_1KG -w 10000 -s 10000   -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.output.txt 
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.0.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.0.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFI_REGION_1KG.vcf.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFI_REGION_1KG.gz -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFI_REGION_1KG -w 10000 -s 10000   -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.output.txt 
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.0.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.0.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C2_REGION_1KG.vcf.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C2_REGION_1KG.gz -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C2_REGION_1KG -w 10000 -s 10000   -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.output.txt 
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.0.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.0.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C3_REGION_1KG.vcf.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C3_REGION_1KG.gz -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C3_REGION_1KG -w 10000 -s 10000   -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.output.txt 
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.0.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param0.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.0.OK 
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep paramtemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/paramtemp0.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep hyptemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp0.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep log | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/log0.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param0.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param0.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/pre_em.OK
	Rscript --no-save --no-restore --verbose /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Mstep.r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp0.txt 0 1e-6 0.1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current >> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.1.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFH_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFH_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFH_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.1.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.1.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFI_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFI_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFI_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.1.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.1.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C2_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C2_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C2_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.1.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.1.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R0.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C3_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C3_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C3_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.1.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param1.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.1.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.1.OK 
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep paramtemp | sort ` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/paramtemp1.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep hyptemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp1.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep log | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/log1.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param1.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param1.OK
	Rscript --no-save --no-restore --verbose /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Mstep.r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp1.txt 1 1e-6 0.1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current >> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.2.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFH_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFH_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFH_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.2.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.2.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFI_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFI_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFI_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.2.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.2.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C2_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C2_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C2_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.2.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.2.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R1.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C3_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C3_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C3_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.2.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param2.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.2.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.2.OK 
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep paramtemp | sort ` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/paramtemp2.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep hyptemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp2.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep log | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/log2.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param2.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param2.OK
	Rscript --no-save --no-restore --verbose /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Mstep.r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp2.txt 2 1e-6 0.1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current >> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.3.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFH_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFH_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFH_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.3.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.3.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFI_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFI_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFI_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.3.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.3.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C2_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C2_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C2_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.3.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.3.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R2.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C3_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C3_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C3_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.3.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param3.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.3.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.3.OK 
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep paramtemp | sort ` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/paramtemp3.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep hyptemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp3.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep log | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/log3.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param3.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param3.OK
	Rscript --no-save --no-restore --verbose /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Mstep.r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp3.txt 3 1e-6 0.1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current >> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.4.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFH_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFH_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFH_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.4.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.4.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFI_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFI_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFI_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.4.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.4.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C2_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C2_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C2_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.4.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.4.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R3.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C3_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C3_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C3_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.4.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param4.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.4.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.4.OK 
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep paramtemp | sort ` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/paramtemp4.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep hyptemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp4.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep log | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/log4.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param4.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param4.OK
	Rscript --no-save --no-restore --verbose /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Mstep.r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp4.txt 4 1e-6 0.1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current >> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.5.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFH_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFH_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFH_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.5.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.5.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/CFI_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_CFI_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o CFI_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.5.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.5.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C2_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C2_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C2_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.5.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.5.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R4.OK
	srun --exclude= --partition=nomosix,main,assembly --mem-per-cpu=3000 --time=24:00:00 --nice=0 --error=/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/%N.%j.err -J testjob -D /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Estep_mcmc -vcf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/vcfs/C3_REGION_1KG.vcf.gz -a /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/annos/Anno_C3_REGION_1KG.gz -p /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/phenoAMD_1KG.txt -fcode /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/ExData/AnnoCode6.txt -hfile /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current -GTfield GT -maf 0.005 -bvsrm -rmin 1 -rmax 1 -smin 0 -smax 10 -win 100 -o C3_REGION_1KG -w 10000 -s 10000  -initype 3 -rv 1 > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.output.txt  
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.5.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param5.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFH_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/CFI_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C2_REGION_1KG.5.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/C3_REGION_1KG.5.OK 
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep paramtemp | sort ` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/paramtemp5.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep hyptemp | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp5.txt
	cat `ls -d -1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/output/** | grep log | sort` > /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/log5.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param5.OK

/net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R5.OK: /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/cp_param5.OK
	Rscript --no-save --no-restore --verbose /net/fantasia/home/yjingj/GIT/bfGWAS/bin/Mstep.r /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/hyptemp5.txt 5 1e-6 0.1 /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/EM_result.txt /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/hypval.current >> /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Rout.txt
	touch /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/R5.OK

clean_err: 
	-rm -rf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/*.err
clean: 
	-rm -rf /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/*.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/Eoutput/*.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/OUT/*.OK /net/fantasia/home/yjingj/GIT/bfGWAS/1KG_example/Test_Wkdir/slurm_err/*.err
